### PR TITLE
Improved readme

### PR DESCRIPTION
**Pull request by Kralizek**
Added more information about this repo and a set of instructions.

### CODE REVIEW

**Comment by Kralizek** [comment]
@JavierRueda @agnerh this is a pull request for a new feature. It should be merged into `develop`.

**Comment by agnerh** [comment]
@Kralizek What are we supposed to review here?

**Comment by Kralizek** [comment]
Nothing really. It was for you guys to play around with git flow and forks.

**Comment by agnerh** [comment]
Okay, @JavierRueda is there anything you want to do here or can we close the PR?

**Comment by agnerh** [comment]
@Kralizek as there is no input from @JavierRueda I thinks it's fine if we close this one

**Pull request closed without merging**
